name: Build and Publish All AUR Packages

on:
  push:
    branches: [ main ]

jobs:
  environment:
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-environment'
    secrets: &aur_secrets
      HOST: ${{ secrets.OPENBSD_HOST }}
      USER: ${{ secrets.OPENBSD_USER }}
      SSH_KEY: ${{ secrets.OPENBSD_SSH_KEY }}
      GPG_PRIVATE_KEY: ${{ secrets.OPENBSD_GPG_PRIVATE_KEY }}
      GPG_KEYID: ${{ secrets.OPENBSD_GPG_KEY_ID }}
      GPG_PASSPHRASE: ${{ secrets.OPENBSD_GPG_PASSPHRASE }}

  make:
    needs: environment
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-make'
      deps: 'mingw-w64-environment'
    secrets: *aur_secrets

  xxhash:
    needs: [make]
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-xxhash'
      deps: 'mingw-w64-make,mingw-w64-crt'
    secrets: *aur_secrets

  pkg-config:
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-pkg-config'
    secrets: *aur_secrets

  configure:
    needs: [environment, pkg-config]
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-configure'
      deps: 'mingw-w64-pkg-config,mingw-w64-environment'
    secrets: *aur_secrets

  termcap:
    needs: [configure]
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-termcap'
      deps: 'mingw-w64-configure,mingw-w64-crt'
    secrets: *aur_secrets

  libiconv:
    needs: [configure]
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-libiconv'
      deps: 'mingw-w64-configure,mingw-w64-crt'
    secrets: *aur_secrets

  libunistring:
    needs: [configure, libiconv]
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-libunistring'
      deps: 'mingw-w64-configure,mingw-w64-crt,mingw-w64-libiconv'
    secrets: *aur_secrets

  gettext:
    needs: [configure, libunistring, termcap]
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-gettext'
      deps: 'mingw-w64-configure,mingw-w64-libunistring,mingw-w64-termcap'
    secrets: *aur_secrets

  mman:
    needs: [cmake]
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-mman-win32-git'
      deps: 'mingw-w64-environment,mingw-w64-cmake,mingw-w64-crt'
    secrets: *aur_secrets

  glew:
    needs: [cmake]
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-glew'
      deps: 'mingw-w64-cmake,mingw-w64-crt'
    secrets: *aur_secrets

  zlib:
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-zlib'
    secrets: *aur_secrets

  libpng:
    needs: [configure, zlib]
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-libpng'
      deps: 'mingw-w64-configure,mingw-w64-zlib'
    secrets: *aur_secrets

  cmake:
    needs: [environment, pkg-config]
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-cmake'
      deps: 'mingw-w64-environment,mingw-w64-pkg-config'
    secrets: *aur_secrets

  glfw:
    needs: cmake
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-glfw'
      deps: 'mingw-w64-cmake'
    secrets: *aur_secrets

  py-ldd:
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'python-mingw-ldd'
    secrets: *aur_secrets

  ntldd:
    needs: py-ldd
    uses: tty-pt/ci/.github/workflows/aur.yml@main
    with:
      name: 'mingw-w64-ldd'
      deps: 'python-mingw-ldd'
    secrets: *aur_secrets
